### ISSUE TITLE
Existing field value is not returned when fallback page is given

### ISSUE THREAD

**Issue by moritzebeling** [plain-solutions-gmbh/kirby-inherit#1]
Hi, thank you for this plugin. It seems as if the plugin would work properly when no fallback page is given and the inheritance populates upwards until `$site`. Nice!

But when I set a fallback page `$page->my_field( $site->homePage() )` it directly returns the value not from the current page but from the home page.

When looking at the code it seems to me that there might me a case where the current field value exists, but the inheritance is triggered anyway. Maybe it would help to return the current field value at the very top:

```php
function ($field, $page = null) {

	if( $field->isNotEmpty() ){
		return $field;
	}
	
	// ...

}
```

**Comment by plain-solutions-gmbh** [comment]
Hi. Thank for your input. I just implemented that in version 1.0.1.
Greetings.
